version: '3'

tasks:

  install-homebrew:
    desc: 'Installs Homebrew package manager'
    cmds:
      - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  setup-terminal:
    desc: 'Install zsh and oh-my-zsh'
    deps: [install-homebrew]
    vars:
      TASK_LOC:
        sh: where task
    cmds:
      - brew install chezmoi fzf git tmux zsh
      - chsh -s /opt/homebrew/bin/zsh
      - sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      - git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
      - rm -rf {{.TASK_LOC}} && brew install go-task

  install-binaries:
    desc: 'Install binaries with Homebrew'
    vars:
      TERMINAL_TOOLS:
        bat btop chezmoi eza fzf git jq the_silver_searcher tmux wget zsh
      LANGUAGES:
        go rust typst 
      LANGUAGE_TOOLS:
        cmake cocoapods
      SERVICES:
        go-task
      CASK_BINARIES:
        alt-tab android-platform-tools flutter font-jetbrains-mono-nerd-font
        miniforge rectangle
    cmds:
      - brew install {{.TERMINAL_TOOLS}}
      - brew install {{.LANGUAGES}}
      - brew install {{.LANGUAGE_TOOLS}}
      - brew install {{.SERVICES}}
      - brew install --cask {{.CASK_BINARIES}}

  install-home-binaries:
    desc: 'Install binaries for home laptop'
    deps: [install-binaries]
    vars:
      HOME_BINARIES:
        bitwarden-cli podman
      HOME_CASK_BINARIES:
        syncthing tailscale
    cmds:
      - brew install {{.HOME_BINARIES}}
      - brew install --cask {{.HOME_CASK_BINARIES}}
  
  install-apps:
    desc: 'Install applications with Homebrew'
    vars:
      MUSIC_APPS:
        native-access plex rode-central tidal vlc
      PRODUCTIVITY_APPS:
        firefox jabref logi-options-plus obsidian visual-studio-code
      MESSAGING_APPS:
        telegram-desktop whatsapp zoom
      GAMING_APPS:
        discord prismlauncher steam
    cmds:
      - brew install --cask {{.MUSIC_APPS}}
      - brew install --cask {{.PRODUCTIVITY_APPS}}
      - brew install --cask {{.MESSAGING_APPS}}
      - brew install --cask {{.GAMING_APPS}}

