#!/bin/sh

# regex to validate in commit msg
commit_regex="^(feat|fix|docs|style|refactor|perf|test)(\(.+\))?: .+$"

if ! grep -iqE "$commit_regex" "$1"; then
    echo "Aborting commit."  >&2
    echo "Commits should be of the form 'type(scope): message' where type is one of the following:"  >&2
    echo "  feat:     A new feature"  >&2
    echo "  fix:      A bug fix"  >&2
    echo "  docs:     Documentation only changes"  >&2
    echo "  style:    Non-code changes (white-space, formatting, missing semi-colons, etc)"  >&2
    echo "  refactor: A code change that neither fixes a bug nor adds a feature"  >&2
    echo "  perf:     A code change that improves performance"  >&2
    echo "  test:     Adding missing tests or correcting existing tests"  >&2
    exit 1
fi

