format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$character"""

right_format = """
$cmd_duration\
$python\
$rust\
$golang\
$time"""

[hostname]
ssh_symbol = " "

[directory]
style = 'blue'
format = '[ $path]($style)[$read_only]($read_only_style) '
truncate_to_repo = false
truncation_length = 4
truncation_symbol = '…/'

[git_branch]
style = 'green'
symbol = '  '
[git_status]
style = 'blue'
staged = '[+$count](yellow) '
ahead = '[⇡$count](green) '
behind = '[⇣$count](green) '
format = '([$all_status$ahead_behind]($style))'

[cmd_duration]
style = 'yellow'
format = 'took [ $duration]($style) '

[python]
style = 'cyan'
symbol = ' '
python_binary = ['uv run python', 'python']
detect_files = ['pyproject.toml', 'uv.lock']

[os]
style = 'bold white'
disabled = false
[os.symbols]
Debian = " "
Macos = " "
Android = " "

[golang]
style = 'blue'
format = '[$symbol($version )]($style)'
symbol = ' '

[rust]
style = 'red'
format = '[$symbol($version )]($style)'
symbol = " "

[time]
disabled = false
style = 'cyan'
format = 'at [ $time]($style)'
